# Pytorch!




In [31]:
import torch
print(torch.__version__)

2.9.0+cpu


In [32]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, Using CPU")

GPU is not available, Using CPU


#Creating a Tensor -

In [41]:
# using empty - (2,3) is the size i.e 2/3 array

a = torch.empty(2,3)

tensor([[7.6389e-28, 0.0000e+00, 3.3839e-25],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [34]:
# check type

type(a)

torch.Tensor

In [35]:
# using zeros -all values will be 0

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [36]:
# using ones -all values will be 1

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
# using rand -created tensor with random values

torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [38]:
# use of seed - If u want the same random matrix each time u run use seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [39]:
# using tensor - can customize tensor values

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
# other ways

# arange - u can provide and step if u want to jump ex-(0,10)is range and 2 is step

print("using arange -", torch.arange(0,10,2))

#using linspace -linspace = linearly space..here u can give range like (0,10) and no. of values u want in the range like 10
# -so we got 10 linearly spaced values in range of 0,10

print(" ")
print("using linspace -",torch.linspace(0,10,10))

#using eye - here the diagonal items will be 1 and 5 is the size

print(" ")
print("using eye -", torch.eye(5))

#using full - (3,3) is size and 5 is the value

print(" ")
print("using full -", torch.full((3,3), 5))

using arange - tensor([0, 2, 4, 6, 8])
 
using linspace - tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
 
using eye - tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
 
using full - tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes -

In [50]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [49]:
x.shape

torch.Size([2, 3])

In [51]:
#empy_like -makes another tensor with same shape as given tensor x

torch.empty_like(x)

tensor([[              0,       382584272,       364427216],
        [138892890369120,               1,               6]])

In [52]:
#zeros_like -here all values will be 0

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [53]:
#ones_like -all valueswill be 1

torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])