# Pytorch!




In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, Using CPU")

GPU is available
Using GPU: Tesla T4


#Creating a Tensor -

In [4]:
# using empty - (2,3) is the size i.e 2/3 array

a = torch.empty(2,3)

In [5]:
# check type

type(a)

torch.Tensor

In [6]:
# using zeros -all values will be 0

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones -all values will be 1

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand -created tensor with random values

torch.rand(2,3)

tensor([[0.3159, 0.3555, 0.2919],
        [0.0696, 0.6862, 0.5905]])

In [9]:
# use of seed - If u want the same random matrix each time u run use seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor - can customize tensor values

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange - u can provide and step if u want to jump ex-(0,10)is range and 2 is step

print("using arange -", torch.arange(0,10,2))

#using linspace -linspace = linearly space..here u can give range like (0,10) and no. of values u want in the range like 10
# -so we got 10 linearly spaced values in range of 0,10

print(" ")
print("using linspace -",torch.linspace(0,10,10))

#using eye - here the diagonal items will be 1 and 5 is the size

print(" ")
print("using eye -", torch.eye(5))

#using full - (3,3) is size and 5 is the value

print(" ")
print("using full -", torch.full((3,3), 5))

using arange - tensor([0, 2, 4, 6, 8])
 
using linspace - tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
 
using eye - tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
 
using full - tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes -

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
#empy_like -makes another tensor with same shape as given tensor x

torch.empty_like(x)

tensor([[663615241,         0,         0],
        [       97, 626934384, 629233008]])

In [15]:
#zeros_like -here all values will be 0

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
#ones_like -all valueswill be 1

torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
#rand_like - here you have to mention datatype as float to get random values in range

torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Datatypes -

In [18]:
#find datatype
x.dtype

torch.int64

In [19]:
# assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
#using to -can change datatype of tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations -

In [22]:
#addition
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [23]:
#Substraction
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [24]:
#Multiplication
x*3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [25]:
#division
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [26]:
#int division
(x*100)//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [27]:
#mod
((x*100)//3)%2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [28]:
#power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

# Element Wise Operation -

In [29]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [30]:
#addition
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [31]:
#substraction
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [32]:
#multiply
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [33]:
#division
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [34]:
#power
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [35]:
#mod
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [36]:
c = torch.tensor([-1,-2,-3,-4])

#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
#negative
d = torch.tensor([1,2,3])
torch.neg(d)

tensor([-1, -2, -3])

In [38]:
e =torch.tensor([1.9,2.3,3.7,4.4])

#round
torch.round(e)

tensor([2., 2., 4., 4.])

In [39]:
#ceil
torch.ceil(e)

tensor([2., 3., 4., 5.])

In [40]:
#floor
torch.floor(e)

tensor([1., 2., 3., 4.])

In [41]:
#clamp -can keep all no.'s in a defined range, so smaller than min will become min and greater than min willl become max
torch.clamp(e, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction Operation -

In [42]:
f = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
f

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [43]:
#sum
torch.sum(f)

tensor(27.)

In [44]:
#sum along columns
torch.sum(f,dim=0)

tensor([9., 9., 9.])

In [45]:
#sum along rows
torch.sum(f,dim=1)

tensor([10., 17.])

In [46]:
#mean
torch.mean(f)

tensor(4.5000)

In [47]:
#mean along col
torch.mean(f,dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [48]:
#median
torch.median(f)

tensor(1.)

In [49]:
#max and min
torch.max(f)
torch.min(f)

tensor(0.)

In [50]:
#product
torch.prod(f)

tensor(0.)

In [51]:
#standard deviation
torch.std(f)

tensor(4.5935)

In [52]:
#variation
torch.var(f)

tensor(21.1000)

In [53]:
#argmax - tells position of biggest element/no.
torch.argmax(f)

tensor(2)

In [54]:
#argmin - tells position of smallest element/no.
torch.argmin(f)

tensor(0)

# Matrix Operations -

In [55]:
g = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
h = torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)
print(g)
print(h)

tensor([[7., 0., 0.],
        [9., 5., 7.]])
tensor([[3., 9.],
        [4., 0.],
        [5., 7.]])


In [56]:
#matrix multplication
torch.matmul(g,h)

tensor([[ 21.,  63.],
        [ 82., 130.]])

In [57]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [58]:
#transpose - (name of matrix -g, swip 0, swipe with 1)
torch.transpose(g,0,1)

tensor([[7., 9.],
        [0., 5.],
        [0., 7.]])

# Comparison Operations

In [59]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[5, 9, 9],
        [7, 5, 9]])
tensor([[8, 9, 7],
        [9, 2, 6]])


In [60]:
#greater than
i>j

tensor([[False, False,  True],
        [False,  True,  True]])

In [61]:
#less than
i<j

tensor([[ True, False, False],
        [ True, False, False]])

In [62]:
#equal to
i == j

tensor([[False,  True, False],
        [False, False, False]])

In [63]:
#not equal to
i!=j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [64]:
#greater than equal to
i>=j

tensor([[False,  True,  True],
        [False,  True,  True]])

In [65]:
#less than equal to
i<=j

tensor([[ True,  True, False],
        [ True, False, False]])

##  Special Functions -

In [66]:
k = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
k

tensor([[7., 7., 8.],
        [3., 6., 1.]])

In [67]:
#log
torch.log(k)

tensor([[1.9459, 1.9459, 2.0794],
        [1.0986, 1.7918, 0.0000]])

In [68]:
#exp
torch.exp(k)

tensor([[1.0966e+03, 1.0966e+03, 2.9810e+03],
        [2.0086e+01, 4.0343e+02, 2.7183e+00]])

In [69]:
#sqrt
torch.sqrt(k)

tensor([[2.6458, 2.6458, 2.8284],
        [1.7321, 2.4495, 1.0000]])

In [70]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9991, 0.9997],
        [0.9526, 0.9975, 0.7311]])

In [71]:
#softmax
torch.softmax(k,dim=0)

tensor([[9.8201e-01, 7.3106e-01, 9.9909e-01],
        [1.7986e-02, 2.6894e-01, 9.1105e-04]])

In [72]:
#relu
torch.relu(k)

tensor([[7., 7., 8.],
        [3., 6., 1.]])

# Inplace Operations -

In [73]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])
tensor([[0.7775, 0.6179, 0.3379],
        [0.2170, 0.9454, 0.7116]])


In [74]:
#makes changes in existing tensors after operations are performed - a=a+b
m.add_(n)

tensor([[1.0814, 1.2905, 0.9118],
        [1.1403, 1.8632, 1.4706]])

# Copying a Tensor -

In [75]:
a = torch.rand(2,3)
a

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [76]:
#using this u create exact copy-even after making changes to origninal it will reflect in copied tensor
b=a
b

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [77]:
#see as i make changes in a same will reflect in b
a[0][0]=0
print(a)
print(b)


tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])
tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])


In [78]:
# this is not feasible all the time as b is just another pointer pointing to a (same memory location)
print("A= ",id(a))
print("B= ",id(b))

A=  139521558254912
B=  139521558254912


In [79]:
#hence we can use function - clone

b = a.clone()
print(a)
print(b)

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])
tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])


In [80]:
a[0][0] = 10
a

tensor([[10.0000,  0.6574,  0.3451],
        [ 0.0453,  0.9798,  0.5548]])

In [81]:
#this is because by using clone it has created a copy on another menmory location
print(b)
print("A= ",id(a))
print("B= ",id(b))

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])
A=  139521558254912
B=  139521558259712


# Tensor Operations on GPU -

In [82]:
torch.cuda.is_available()

True

In [84]:
# create variable to store GPU
device = torch.device('cuda')

In [85]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [89]:
#moving an existing tensor to GPU

#using to function
a = torch.rand((2,3))
b = a.to(device)
b

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]], device='cuda:0')

# Reshaping Tensors -

In [90]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [91]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [92]:
#flatten -converts everything to 1D tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [93]:
b = torch.rand(2,3,4)
b

tensor([[[0.5224, 0.4175, 0.0340, 0.9157],
         [0.3079, 0.6269, 0.8277, 0.6594],
         [0.0887, 0.4890, 0.5887, 0.7340]],

        [[0.8497, 0.9112, 0.4847, 0.9436],
         [0.3904, 0.2499, 0.3206, 0.9753],
         [0.7582, 0.6688, 0.2651, 0.2336]]])

In [95]:
#permute -I want to bring 2nd dimension 1st, 0th in center, and 1st to last
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [96]:
#unsqueeze -adds new dimension on a given position
#image size - (226,226,3)

c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [97]:
#squeeze - It remover said dimension i.e. squeezes

d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and PyTorch -

In [99]:
import numpy as np

In [100]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [102]:
# How to convert Pytorch tensor into Numpy aaray
b = a.numpy()
print(b)
type(b)

[1 2 3]


numpy.ndarray

In [103]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [108]:
# To convert np array to Pytorch tensor

torch.from_numpy(c)
print(c)
type(c)

[1 2 3]


numpy.ndarray